spring.datasource.url: jdbc:mysql://localhost:3306/socialnet?serverTimezone=UTC&&useSSL=false
spring.datasource.username: root
spring.datasource.password: rootroot
spring.jpa.hibernate.ddl-auto: create
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect