databaseChangeLog:
  - logicalFilePath: db.changelog/db.changelog-create-global-settings.yaml
  - changeSet:
      id: 2
      author: master
      changes:
          - createTable:
              tableName: global_settings
              columns:
                - column:
                    name: id
                    type: int(11)
                    autoIncrement: true
                    constraints:
                      primaryKey: true
                      nullable: false
                - column:
                    name: code
                    type: varchar (255)
                    constraints:
                      nullable: false
                - column:
                    name: name
                    type: varchar (255)
                    constraints:
                      nullable: false
                - column:
                    name: value
                    type: varchar (255)
                    constraints:
                      nullable: false