databaseChangeLog:
  - logicalFilePath: db.changelog/db.changelog-insert-params-into-global-settings.yaml
  - changeSet:
      id: 19
      author: master
      changes:
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: code
                  value: "1"
              - column:
                  name: name
                  value: "MULTIUSER_MODE"
              - column:
                  name: value
                  value: "true"
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: code
                  value: "2"
              - column:
                  name: name
                  value: "POST_PREMODERATION"
              - column:
                  name: value
                  value: "true"
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: code
                  value: "3"
              - column:
                  name: name
                  value: "STATISTICS_IS_PUBLIC"
              - column:
                  name: value
                  value: "true"